### JWT
GET http://localhost:8080/auth/login?username=alice&role=user
Content-Type: */*

### JWT
GET http://localhost:8080/auth/login?username=bob&role=admin
Content-Type: */*

### JWT
GET http://localhost:8080/auth/login?username=carol&role=user&role=admin
Content-Type: */*

### JWT
GET http://localhost:8080/secured/public/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3F1YXJrdXMuaW8vand0LWNhc2UiLCJ1cG4iOiJib2IiLCJncm91cHMiOlsiYWRtaW4iXSwiaWF0IjoxNzQ5NTg5MDM4LCJleHAiOjE3NDk1OTI2MzgsImp0aSI6IjUyNGFjMTRiLTg0NGItNGVhYS1hZmE0LTcyMmQyY2VkYzdhNSJ9.ftPrcwOwVPP1fAG-yMyFav5HKs4Dyih7yeuc8u885i8QOan4lB0SJuv2WZO62lrS60NI5o1nnJoLycHJ62z0J3P_5w78dGR4wWFGIWJMofBr1n0lsfulmIJgCvzGIWpePZot3MGfSIgL_uZ50PPNq8tv_8WsLCw0neoz_L5C9Xa6aTdVFdpwxHGANJe761fehDVz-UgVvmeUQrdwmpxnZ9srU1bwbXNpgsin55H5_kTmprMxdGgKQ19uW0wMInlp2vhWSRPXjBMkxU-ESeV1oYUnkCg_NV1qH1ZmWPfuW014_hQ4xONaLiKJu0AwqWllx6l3ueC5Yo3j4Bvhd3KOdA
Content-Type: */*

### JWT
GET http://localhost:8080/secured/hello
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3F1YXJrdXMuaW8vand0LWNhc2UiLCJ1cG4iOiJib2IiLCJncm91cHMiOlsiYWRtaW4iXSwiaWF0IjoxNzQ5NTg5MDM4LCJleHAiOjE3NDk1OTI2MzgsImp0aSI6IjUyNGFjMTRiLTg0NGItNGVhYS1hZmE0LTcyMmQyY2VkYzdhNSJ9.ftPrcwOwVPP1fAG-yMyFav5HKs4Dyih7yeuc8u885i8QOan4lB0SJuv2WZO62lrS60NI5o1nnJoLycHJ62z0J3P_5w78dGR4wWFGIWJMofBr1n0lsfulmIJgCvzGIWpePZot3MGfSIgL_uZ50PPNq8tv_8WsLCw0neoz_L5C9Xa6aTdVFdpwxHGANJe761fehDVz-UgVvmeUQrdwmpxnZ9srU1bwbXNpgsin55H5_kTmprMxdGgKQ19uW0wMInlp2vhWSRPXjBMkxU-ESeV1oYUnkCg_NV1qH1ZmWPfuW014_hQ4xONaLiKJu0AwqWllx6l3ueC5Yo3j4Bvhd3KOdA
Content-Type: */*















###
POST http://localhost:8080/hello
Content-Type: application/json

{
  "name": "New Awesome Item",
  "description": "From curl"
}

###
GET http://localhost:8080/hello/1dc4ca0e-2763-41fa-a4e7-8a4fe3b400b0

###
GET http://localhost:8080/hello/empty
Content-Type: application/json

###
GET http://localhost:8080/hello/itemById/2
Content-Type: application/json

###
GET http://localhost:8080/hello/withCustomHeaders
Content-Type: application/json

###
GET http://localhost:8080/hello/mappedError/5
Content-Type: application/json

###
GET http://localhost:8080/hello/error
Content-Type: application/json

###
GET http://localhost:8080/hello/api/error
Content-Type: application/json

###
GET http://localhost:8080/hello/custom-error
Content-Type: application/json
