### swagger ui
http://localhost:8080/q/graphql-ui

### swagger ui
http://localhost:8080/q/dev-ui/io.quarkus.quarkus-smallrye-openapi/swagger-ui

### hello
GET http://localhost:8080/hello
Content-Type: */*

### JWT
GET http://localhost:8080/auth/login?username=alice&role=twitterUser
Content-Type: */*

### JWT
GET http://localhost:8080/auth/login?username=bob&role=admin
Content-Type: */*

### JWT
GET http://localhost:8080/auth/login?username=carol&role=twitterUser&role=admin
Content-Type: */*

### JWT
GET http://localhost:8080/secured/public/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3F1YXJrdXMuaW8vand0LWNhc2UiLCJ1cG4iOiJib2IiLCJncm91cHMiOlsiYWRtaW4iXSwiaWF0IjoxNzQ5NTg5MDM4LCJleHAiOjE3NDk1OTI2MzgsImp0aSI6IjUyNGFjMTRiLTg0NGItNGVhYS1hZmE0LTcyMmQyY2VkYzdhNSJ9.ftPrcwOwVPP1fAG-yMyFav5HKs4Dyih7yeuc8u885i8QOan4lB0SJuv2WZO62lrS60NI5o1nnJoLycHJ62z0J3P_5w78dGR4wWFGIWJMofBr1n0lsfulmIJgCvzGIWpePZot3MGfSIgL_uZ50PPNq8tv_8WsLCw0neoz_L5C9Xa6aTdVFdpwxHGANJe761fehDVz-UgVvmeUQrdwmpxnZ9srU1bwbXNpgsin55H5_kTmprMxdGgKQ19uW0wMInlp2vhWSRPXjBMkxU-ESeV1oYUnkCg_NV1qH1ZmWPfuW014_hQ4xONaLiKJu0AwqWllx6l3ueC5Yo3j4Bvhd3KOdA
Content-Type: */*

### JWT
GET http://localhost:8080/secured/hello
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3F1YXJrdXMuaW8vand0LWNhc2UiLCJ1cG4iOiJib2IiLCJncm91cHMiOlsiYWRtaW4iXSwiaWF0IjoxNzQ5NTg5MDM4LCJleHAiOjE3NDk1OTI2MzgsImp0aSI6IjUyNGFjMTRiLTg0NGItNGVhYS1hZmE0LTcyMmQyY2VkYzdhNSJ9.ftPrcwOwVPP1fAG-yMyFav5HKs4Dyih7yeuc8u885i8QOan4lB0SJuv2WZO62lrS60NI5o1nnJoLycHJ62z0J3P_5w78dGR4wWFGIWJMofBr1n0lsfulmIJgCvzGIWpePZot3MGfSIgL_uZ50PPNq8tv_8WsLCw0neoz_L5C9Xa6aTdVFdpwxHGANJe761fehDVz-UgVvmeUQrdwmpxnZ9srU1bwbXNpgsin55H5_kTmprMxdGgKQ19uW0wMInlp2vhWSRPXjBMkxU-ESeV1oYUnkCg_NV1qH1ZmWPfuW014_hQ4xONaLiKJu0AwqWllx6l3ueC5Yo3j4Bvhd3KOdA
Content-Type: */*

### errors
http://localhost:8080/error → HTML error

### errors
GET http://localhost:8080/api/error
Content-Type: application/json

### errors
GET http://localhost:8080/custom-error
Content-Type: application/json

### filters
GET http://localhost:8080/filters
Content-Type: */*

### filters
GET http://localhost:8080/filters/audited
Content-Type: */*

### restResponse
GET http://localhost:8080/items/simple/1
Content-Type: application/json

### restResponse
GET http://localhost:8080/items/simple-list
Content-Type: application/json

### restResponse
GET http://localhost:8080/items/direct/1
Content-Type: application/json

### restResponse
POST http://localhost:8080/items
Content-Type: application/json

{
  "id": "1",
  "name": "New Awesome Item",
  "description": "From curl"
}

### restResponse
GET http://localhost:8080/items/with-headers
Content-Type: application/json

### restResponse
GET http://localhost:8080/items/notfoundexample/5
Content-Type: application/json

### restResponse
GET http://localhost:8080/items/0
Content-Type: application/json

### flyway
POST http://localhost:8080/people
Content-Type: application/json

{
  "name": "Alice",
  "email": "alice@example.com"
}

### flyway
GET http://localhost:8080/people
Content-Type: application/json

### secure authentication jpa
GET http://localhost:8080/secured-api/admin
Content-Type: application/json
Authorization: Basic YWxpY2U6YWxpY2VQYXNzd29yZA==

### secure authentication jpa
GET http://localhost:8080/secured-api/twitterUser
Content-Type: application/json
Authorization: Basic YWxpY2U6YWxpY2VQYXNzd29yZA==

### secure authentication jpa
GET http://localhost:8080/secured-api/public
Content-Type: application/json

### tenant
POST http://localhost:8080/api/todos
accept: */*
Authorization: Basic YWxpY2U6YWxpY2VwYXNzd29yZA==
Content-Type: application/json

{
  "title": "Buy lembas bread"
}

### tenant
GET http://localhost:8080/api/todos
accept: */*
Authorization: Basic YWxpY2U6YWxpY2VwYXNzd29yZA==

### tenant
GET http://localhost:8080/api/todos/1
accept: */*
Authorization: Basic Ym9iOmJvYnBhc3N3b3Jk

### rate limit (global)
# curl http://localhost:8080/api/v1/metrics/cpu
GET http://localhost:8080/api/v1/metrics/cpu

### rate limit (by tenant id)
GET http://localhost:8080/api/v1/metrics/memory
accept: */*
X-Tenant-ID: tenant-b

### rate limit (pro and free)
GET http://localhost:8080/api/v1/reports/generate
Content-Type: */*
X-Tenant-ID: tenant-free-twitterUser

### rate limit (pro and free)
GET http://localhost:8080/api/v1/reports/generate
Content-Type: */*
X-Tenant-ID: tenant-pro-twitterUser



